# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98413c7b682c24f031130e647f4b18490befdb73d0b514dca5dabd36a0247f937420b27d2318053f79d656c429cc6a3b2569b883495de14d3ac8b347d6fbfdf5

test:
  secret_key_base: 80d43042bfab6bc940b20dcdef8541615187f33d2761a9456c1e25bf89f0dd583285f3bfb59fc5911b4f291532604c664dd78b7e6bc3143244338d4f11f22b2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
